# Generated by Django 4.0 on 2022-09-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseComment',
            new_name='CourseCommentModel',
        ),
        migrations.RenameModel(
            old_name='CourseHeadlines',
            new_name='CourseHeadlinesModel',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='video_cover',
            field=models.ImageField(null=True, upload_to='course/courseCover'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='video_link',
            field=models.URLField(max_length=400),
        ),
    ]
