# Generated by Django 4.0 on 2022-09-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_coursecomment_coursecommentmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='video_cover',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
