# Generated by Django 4.0 on 2022-09-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseheadlinesmodel',
            name='video_link',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
