# Generated by Django 4.0 on 2022-09-08 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_courseheadlinesmodel_video_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseModel',
            new_name='CoursePreviewModel',
        ),
        migrations.RemoveField(
            model_name='coursecommentmodel',
            name='course_id',
        ),
        migrations.AddField(
            model_name='coursecommentmodel',
            name='headline_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.courseheadlinesmodel'),
        ),
        migrations.AddField(
            model_name='courseheadlinesmodel',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='courseheadlinesmodel',
            name='video_cover',
            field=models.ImageField(blank=True, null=True, upload_to='headline'),
        ),
    ]
