# Generated by Django 4.0 on 2022-09-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivePLan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_plan_active', models.BooleanField()),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.planmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
